[book]
authors = ["Seasawher"]
language = "ja"
multilingual = false
src = "SRC"
title = "Lean By Example"
description = "Lean Prover の短いコード例を解説付きで集めたものです．"

[build]
create-missing = false
build-dir = "book"

[output.html]
additional-js = ["assets/leanweb.js", "assets/fzf.umd.js", "assets/elasticlunr.js", "assets/edit.js"]
git-repository-url = "https://github.com/Seasawher/{repo_name}"
edit-url-template = "https://raw.githubusercontent.com/Seasawher/{repo_name}/main/{path}"
no-section-label = true
