[book]
authors = ["Seasawher"]
language = "ja"
multilingual = false
src = "NTL"
title = "動かして学ぶ Lean Prover"
description = ""

[build]
create-missing = false
build-dir = "book"

[output.html]
additional-js = ["assets/leanweb.js", "assets/fzf.umd.js", "assets/elasticlunr.js", "assets/edit.js"]
git-repository-url = "https://github.com/Seasawher/number-theory-with-lean"
edit-url-template = "https://raw.githubusercontent.com/Seasawher/number-theory-with-lean/main/{path}"
no-section-label = true

[preprocessor.indexing]